name: PR Ready for Review

on:
  pull_request:
    types: [ready_for_review]

jobs:
  notify-reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Notify reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            
            // Add a comment to the PR
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pr.number,
              body: `@${pr.user.login}, this PR is now ready for review. Reviewers will be notified.`
            });
            
            // You can also send notifications via other channels like Slack, email, etc.
            // by integrating with other GitHub Actions
